spring.application.name=url-shortener

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/urlshortener
spring.datasource.username=root
spring.datasource.password=mohit@13

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

spring.data.redis.host=host.docker.internal
spring.data.redis.port=6379
spring.cache.type=redis

logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG